CONTENT_DE = {
    "lang": "de",
    "lang_code": "de",
    "lang_name": "DE",
    "other_lang": "ru",
    "other_lang_name": "RU",

    "brand": "SalesDesk AI",
    "brand_tagline": "KI-Sales-Bot 24/7",
    "brand_full": "SalesDesk AI — KI-Sales-Bot 24/7",

    "nav": {
        "home": "Startseite",
        "solutions": "Lösungen",
        "pricing": "Preise",
        "demo": "Demo",
        "blog": "Blog",
        "cases": "Referenzen",
        "about": "Über uns",
        "contact": "Kontakt",
    },

    "cta": {
        "primary": "Demo anfordern",
        "secondary": "Implementierung besprechen",
        "telegram": "Per Telegram schreiben",
        "self_try": "Selbst ausprobieren",
        "read_more": "Mehr erfahren",
        "all_solutions": "Alle Lösungen",
        "back_to_blog": "Zurück zum Blog",
        # legacy keys
        "try_demo": "Demo anfordern",
        "turnkey": "Implementierung besprechen",
        "self_serve": "Selbst ausprobieren",
        "contact_us": "Implementierung besprechen",
    },

    "cta_micro": "Kostenlos. Unverbindlich. Wir zeigen ein Szenario für Ihre Branche.",

    "trust_strip": [
        "Schlüsselfertige Implementierung",
        "Szenarien für Ihre Branche",
        "Lead-Übergabe an Ihr Team",
        "Telegram / WhatsApp / Instagram*",
    ],
    "trust_strip_note": "*Verfügbarkeit der Kanäle hängt von der gewählten Plattform und den technischen Anbindungsbedingungen ab.",

    "mobile_sticky": {
        "demo": "Demo",
        "telegram": "Telegram",
    },

    "footer": {
        "description": "KI-Automatisierung von Anfragen und Kundendialogen für Unternehmen. Antworten rund um die Uhr, Lead-Qualifizierung und Übergabe an Ihr Team.",
        "trust_copy": "KI-Automatisierung von Anfragen und Kundendialogen für Unternehmen.",
        "nav_title": "Navigation",
        "legal_title": "Rechtliches",
        "contact_title": "Kontakt",
        "privacy": "Datenschutz",
        "terms": "AGB",
        "copyright": "SalesDesk AI. Alle Rechte vorbehalten.",
        "powered_by": "Technologie-Basis: NextBot",
    },

    "home": {
        "meta_title": "KI-Bot für Anfragen und Vertrieb 24/7 | SalesDesk AI",
        "meta_desc": "Der KI-Bot beantwortet Kundenanfragen, qualifiziert Leads und übergibt heiße Dialoge Ihrem Team. Holen Sie sich eine Demo und ein Szenario für Ihre Branche.",

        "hero_title": "Der KI-Bot antwortet Ihren Kunden in Sekunden —",
        "hero_highlight": "auch wenn das Team gerade beschäftigt ist",
        "hero_desc": "SalesDesk AI hilft Ihrem Unternehmen, Anfragen rund um die Uhr zu bearbeiten, häufige Fragen zu beantworten, Kunden zu qualifizieren und heiße Dialoge an Ihr Team zu übergeben. Schlüsselfertige Implementierung ohne komplizierte Konfiguration.",
        "hero_cta_primary": "Demo anfordern",
        "hero_cta_secondary": "Implementierung besprechen",

        "hero_mockup_status_new": "Neue Anfrage",
        "hero_mockup_status_qualified": "Lead qualifiziert",
        "hero_mockup_status_handed": "An Team übergeben",
        "hero_mockup_messages": [
            {"role": "user", "text": "Was kostet eine Maniküre und gibt es heute noch freie Termine?"},
            {"role": "bot", "text": "Maniküre ab 35 €. Heute sind ab 15:00 Uhr noch Plätze frei. Welche Uhrzeit passt Ihnen?"},
            {"role": "user", "text": "16:00 Uhr"},
            {"role": "bot", "text": "Notiert. Auf welchen Namen darf ich den Termin buchen?"},
        ],

        "problems_title": "Kommt Ihnen das bekannt vor?",
        "problems": [
            {"icon": "clock", "title": "Anfragen gehen verloren", "desc": "Ein Kunde schreibt um 23 Uhr — die Antwort kommt erst am nächsten Morgen. Zu spät: Er ist beim Wettbewerb."},
            {"icon": "users", "title": "Ihr Team ist überlastet", "desc": "Die meisten Fragen wiederholen sich. Ihr Vertrieb verbringt Zeit mit FAQ statt mit Abschlüssen."},
            {"icon": "trending-down", "title": "Kein Follow-up", "desc": "Interessenten fragen an und verschwinden. Niemand erinnert, klärt nach oder schließt ab."},
        ],

        "cost_title": "Was kostet eine langsame Antwort?",
        "cost_desc": "Kunden warten nicht. Wenn jetzt niemand antwortet, schreiben sie der Konkurrenz. Der KI-Bot beantwortet erste Fragen, erfasst Kontaktdaten und übergibt dem Team bereits ein warmes Gespräch.",
        "cost_cards": [
            {"title": "Anfragen nachts", "desc": "Anfragen kommen, wenn niemand erreichbar ist. Ohne Antwort wechselt der Kunde zum Wettbewerb."},
            {"title": "Wiederkehrende Fragen", "desc": "Preise, Öffnungszeiten, Verfügbarkeit, Lieferung. Dieselben Antworten — Dutzende Male am Tag, manuell."},
            {"title": "Team überlastet", "desc": "Anfragenstrom wächst schneller als das Team. Ein Teil der Nachrichten wird gelesen, aber nicht beantwortet."},
        ],

        "solution_title": "So löst SalesDesk AI das",
        "solution_steps": [
            {"icon": "zap", "title": "Sofortantwort", "desc": "Der Bot antwortet in 2–3 Sekunden — zu jeder Tages- und Nachtzeit."},
            {"icon": "filter", "title": "Qualifizierung", "desc": "KI stellt gezielte Fragen, erkennt Bedarf und Kontext. Ihr Team erhält qualifizierte Leads."},
            {"icon": "repeat", "title": "Follow-up", "desc": "Automatische Erinnerungen und Follow-up-Sequenzen. Kein Interessent geht im Chat verloren."},
            {"icon": "user-check", "title": "Übergabe ans Team", "desc": "Wenn der Lead bereit ist — übergibt der Bot das Gespräch mit vollem Kontext an Ihr Team."},
        ],

        "flow_title": "Was in 30 Sekunden passiert",
        "flow_subtitle": "Ein realer Dialog: von der Kundenfrage bis zum qualifizierten Lead in den Händen Ihres Teams.",
        "flow_steps": [
            {"role": "user", "title": "Kunde fragt nach Preis", "desc": "„Was kostet die Leistung und gibt es freie Termine?"},
            {"role": "bot", "title": "KI klärt das Anliegen", "desc": "Der Bot antwortet zum Preis und stellt 1–2 gezielte Rückfragen."},
            {"role": "bot", "title": "KI erfasst den Kontakt", "desc": "Erfragt Name und bevorzugten Kanal, dokumentiert die Anfrage."},
            {"role": "manager", "title": "Team erhält qualifizierten Lead", "desc": "Im CRM/Chat erscheint die Gesprächskarte — mit Kontext und Kontakt."},
        ],

        "industries_title": "Für Ihre Branche optimiert",
        "industries_desc": "SalesDesk AI passt sich an die Anforderungen Ihres Geschäfts an",
        "industries_use_case": "Die KI beantwortet häufige Fragen, klärt das Anliegen, erfasst den Kontakt und übergibt an Ihr Team.",

        "stats_title": "Warum Unternehmen auf KI-Vertrieb setzen",
        "stats": [
            {"value": "24/7", "label": "Verfügbarkeit"},
            {"value": "2–3 Sek", "label": "Antwortzeit"},
            {"value": "24–48 h", "label": "Implementierung"},
            {"value": "DE + RU", "label": "Zweisprachiger Support"},
        ],

        "process_title": "Start in 3 Schritten",
        "process_steps": [
            {"num": "01", "title": "Briefing", "desc": "Beschreiben Sie Ihr Geschäft, Ihre Leistungen und typische Kundenanfragen."},
            {"num": "02", "title": "Einrichtung", "desc": "Wir erstellen Szenarien, laden Ihre Wissensbasis und testen alles gründlich."},
            {"num": "03", "title": "Go-Live", "desc": "Anbindung an Ihre Kanäle und Schulung Ihres Teams."},
        ],

        "guarantee_title": "Transparenter Implementierungsprozess",
        "guarantee_desc": "Klare Schritte, vereinbarte Termine und Begleitung nach dem Go-Live. Verzögert sich der Launch durch unser Verschulden über das Vereinbarte hinaus, erstatten wir die Einrichtungsgebühr.",

        "faq_title": "Häufige Fragen",
        "faq": [
            {"q": "Was ist SalesDesk AI?", "a": "SalesDesk AI ist ein KI-Vertriebsassistent, der rund um die Uhr arbeitet. Er beantwortet Kundenanfragen, qualifiziert Leads und übergibt sie an Ihr Vertriebsteam. Technologische Basis ist die NextBot-Plattform."},
            {"q": "Wie schnell kann ich starten?", "a": "Mit dem schlüsselfertigen Paket in 24–48 Stunden ab Bereitstellung Ihrer Materialien (FAQ, Preisliste, Leistungsbeschreibung). Selbsteinrichtung ab 10 Minuten."},
            {"q": "Ersetzt der Bot meinen Vertrieb?", "a": "Nein. Der Bot übernimmt Routineaufgaben: Erstantworten, Qualifizierung, FAQ. Ihr Team erhält vorqualifizierte Leads und konzentriert sich auf Abschlüsse."},
            {"q": "Welche Kanäle werden unterstützt?", "a": "Telegram, WhatsApp, Instagram Direct, Website-Widget, Facebook Messenger — abhängig vom gewählten Paket und den technischen Anbindungsbedingungen."},
            {"q": "Was passiert bei falschen Antworten?", "a": "Der Bot arbeitet ausschließlich mit Ihrer Wissensbasis. Bei unklaren Anfragen leitet er an einen Mitarbeiter weiter. Vor dem Start testen wir alle Szenarien."},
            {"q": "Was kostet es?", "a": "Es gibt mehrere Formate: vom Selbsttest bis zur vollständigen schlüsselfertigen Implementierung. Details auf der Preisseite."},
        ],

        "inline_form_title": "Wir zeigen eine Demo für Ihre Branche",
        "inline_form_desc": "Hinterlassen Sie Ihren Kontakt — wir schicken ein kurzes Szenario-Beispiel und laden zur Demo ein.",
    },

    "solutions": {
        "meta_title": "SalesDesk AI Lösungen nach Branche | KI-Bot für Ihr Geschäft",
        "meta_desc": "KI-Sales-Bot für Salons, Bildung, Kliniken, Werkstätten, Gastronomie, Immobilien und Einzelhandel. Szenario für Ihre Branche.",
        "title": "Lösungen für Ihre Branche",
        "desc": "SalesDesk AI passt sich an Ihre Branche an. Wählen Sie Ihren Bereich — wir zeigen, wie der KI-Bot bei Ihnen arbeitet.",
        "use_case_label": "So arbeitet der Bot in Ihrer Branche",
        "generic_use_case": "Die KI beantwortet häufige Fragen, klärt das Anliegen, erfasst den Kontakt und übergibt an Ihr Team.",
        "stub_problems_title": "Typische Herausforderungen",
        "stub_flow_title": "Was der KI-Bot übernimmt",
        "stub_flow": [
            {"title": "Beantwortet häufige Fragen", "desc": "Der Bot deckt 70–80 % der typischen Anfragen aus Ihrer Wissensbasis ab."},
            {"title": "Klärt das Anliegen", "desc": "Stellt 1–2 kurze qualifizierende Rückfragen passend zu Ihrer Branche."},
            {"title": "Übergibt einen warmen Lead", "desc": "Im CRM oder Telegram erscheint eine Karte mit Kontakt und Gesprächskontext."},
        ],
        "niches": {
            "beauty": {
                "name": "Kosmetik & Salons",
                "icon": "sparkles",
                "short_desc": "KI-Bot für Schönheitssalons, Kosmetikstudios und Barbershops",
                "use_case": "Die KI berät zu Leistungen, bucht Termine und erinnert an Besuche.",
                "meta_title": "KI-Bot für Schönheitssalons | SalesDesk AI",
                "meta_desc": "Automatisieren Sie Terminbuchungen und Beratungen in Ihrem Salon. KI-Bot antwortet 24/7, bucht Termine und erinnert an Besuche.",
                "hero_title": "KI-Rezeption für Ihren Salon",
                "hero_desc": "Kunden schreiben außerhalb der Öffnungszeiten? Ihre Rezeption kommt nicht hinterher? SalesDesk AI arbeitet rund um die Uhr: berät zu Leistungen und Preisen, bucht Termine und erinnert an Besuche.",
                "problems": [
                    "Kunden schreiben um 22 Uhr — die Antwort kommt erst am nächsten Morgen",
                    "Die Rezeption ist mit Telefonaten überlastet und kann nicht auf Messenger antworten",
                    "Keine automatischen Erinnerungen — Kunden vergessen Termine",
                    "Neukunden erhalten keine Beratung zu Leistungen und gehen woanders hin",
                ],
                "how_it_works": [
                    {"title": "Leistungsberatung", "desc": "Der Bot kennt alle Preise, Behandlungsbeschreibungen und Kontraindikationen. Antwortet sofort auf alle Fragen."},
                    {"title": "Online-Terminbuchung", "desc": "Kunden wählen Behandlung, Mitarbeiter und Wunschtermin direkt im Chat."},
                    {"title": "Erinnerungen", "desc": "Automatische Erinnerung einen Tag und eine Stunde vor dem Termin. Reduziert No-Shows."},
                    {"title": "Übergabe an Mitarbeiter", "desc": "Komplexe Fragen (Allergien, individuelle Behandlungen) werden sofort an die Rezeption weitergeleitet."},
                ],
                "result_title": "Ergebnis",
                "results": [
                    "Anfragen gehen nicht verloren — auch nachts nicht",
                    "Rezeption konzentriert sich auf Kunden vor Ort statt auf Chats",
                    "Weniger No-Shows durch automatische Erinnerungen",
                    "Mehr Buchungen über Messenger und Social Media",
                ],
            },
            "education": {
                "name": "Bildung & Kurse",
                "icon": "graduation-cap",
                "short_desc": "KI-Bot für Online-Schulen, Kurse und Bildungszentren",
                "use_case": "Die KI berät zu Programmen, qualifiziert Interessenten und führt zur Anmeldung.",
                "meta_title": "KI-Bot für Bildung und Kurse | SalesDesk AI",
                "meta_desc": "Automatisieren Sie die Bearbeitung von Kursanfragen. KI-Bot berät zu Programmen, beantwortet Fragen und nimmt Anmeldungen entgegen — 24/7.",
                "hero_title": "KI-Assistent für Ihr Bildungsgeschäft",
                "hero_desc": "Interessenten stellen immer die gleichen Fragen: Programm, Dauer, Kosten, Format. SalesDesk AI übernimmt das — antwortet sofort, hilft bei der Kurswahl und führt zur Anmeldung.",
                "problems": [
                    "Berater beantworten hundertmal täglich die gleichen Fragen",
                    "Anfragen von Website und Social Media werden zu langsam bearbeitet",
                    "Kein Follow-up: Interessent fragt nach einem Kurs und verschwindet",
                    "In der Anmeldesaison ist das Team völlig überlastet",
                ],
                "how_it_works": [
                    {"title": "Programmberatung", "desc": "Der Bot kennt alle Kurse, Zeitpläne, Preise und Formate. Hilft bei der passenden Auswahl."},
                    {"title": "Qualifizierung", "desc": "Ermittelt Vorkenntnisse, Lernziele und Kontext. Empfiehlt die optimale Option."},
                    {"title": "Follow-up", "desc": "Wenn sich der Interessent nicht sofort anmeldet, erinnert der Bot und beantwortet weitere Fragen."},
                    {"title": "Anmeldung", "desc": "Führt zur Kursanmeldung und kann einen Zahlungslink senden."},
                ],
                "result_title": "Ergebnis",
                "results": [
                    "Antwortzeit: Sekunden statt Stunden",
                    "Berater konzentrieren sich auf Verkäufe statt FAQ",
                    "Höhere Konversion von Anfrage zu Anmeldung durch Follow-up",
                    "Skalierung ohne zusätzliche Mitarbeiter",
                ],
            },
            "clinic": {
                "name": "Kliniken & Zahnärzte",
                "icon": "heart-pulse",
                "short_desc": "KI-Bot für medizinische Kliniken und Zahnarztpraxen",
                "use_case": "Die KI vereinbart Termine, beantwortet Fragen zu Leistungen und erinnert Patienten.",
                "meta_title": "KI-Bot für Kliniken und Zahnärzte | SalesDesk AI",
                "meta_desc": "KI-Assistent für medizinische Einrichtungen: Terminbuchung, Leistungsberatung, Patientenerinnerungen. Rund um die Uhr verfügbar.",
                "hero_title": "KI-Assistent für Ihre Praxis",
                "hero_desc": "Patienten schreiben außerhalb der Sprechzeiten? Die Rezeption ist nicht erreichbar? SalesDesk AI beantwortet Fragen, hilft bei der Terminbuchung und erinnert an Termine.",
            },
            "auto": {
                "name": "Autowerkstatt & Teilehandel",
                "icon": "car",
                "short_desc": "KI-Bot für Autowerkstätten und Ersatzteilhändler",
                "use_case": "Die KI nimmt Reparaturanfragen entgegen, klärt das Fahrzeug und bucht Termine.",
                "meta_title": "KI-Bot für Autowerkstätten | SalesDesk AI",
                "meta_desc": "Automatisieren Sie die Auftragsannahme in der Werkstatt. KI-Bot berät zu Leistungen, nimmt Termine an und antwortet 24/7.",
                "hero_title": "KI-Annahme für Ihre Werkstatt",
                "hero_desc": "Kunden fragen nach Preisen und Verfügbarkeit von Teilen? Der KI-Bot nimmt Anfragen rund um die Uhr entgegen, klärt Marke und Problem und bucht Termine.",
            },
            "food": {
                "name": "Gastronomie & Lieferservice",
                "icon": "utensils",
                "short_desc": "KI-Bot für Restaurants, Cafés und Lieferdienste",
                "use_case": "Die KI nimmt Reservierungen, beantwortet Fragen zur Karte und unterstützt Bestellungen.",
                "meta_title": "KI-Bot für Gastronomie | SalesDesk AI",
                "meta_desc": "KI-Assistent für die Gastronomie: Tischreservierung, Speisekarte, Bestellungen. Automatisierung des Bestellprozesses 24/7.",
                "hero_title": "KI-Assistent für Ihr Restaurant",
                "hero_desc": "Gäste schreiben nach Feierabend oder zu Stoßzeiten? Der KI-Bot nimmt Reservierungen entgegen, beantwortet Fragen zur Karte und übergibt komplexe Anliegen an Ihr Team.",
            },
            "real-estate": {
                "name": "Immobilien & Renovierung",
                "icon": "building",
                "short_desc": "KI-Bot für Immobilienagenturen und Renovierungsfirmen",
                "use_case": "Die KI qualifiziert Käufer, schlägt Objekte vor und vereinbart Besichtigungen.",
                "meta_title": "KI-Bot für Immobilien | SalesDesk AI",
                "meta_desc": "Automatisieren Sie die Bearbeitung von Immobilienanfragen. KI-Bot qualifiziert Käufer, schlägt Objekte vor und bucht Besichtigungen.",
                "hero_title": "KI-Berater für Ihre Immobilienagentur",
                "hero_desc": "Es gibt viele Anfragen, aber nicht alle rufen zurück. Der KI-Bot antwortet 24/7, klärt Objektparameter und führt zur Besichtigung.",
            },
            "retail": {
                "name": "Einzelhandel & Technik",
                "icon": "shopping-bag",
                "short_desc": "KI-Bot für Möbel-, Technik- und Einzelhandelsgeschäfte",
                "use_case": "Die KI berät zu Produkten, beantwortet Fragen zur Verfügbarkeit und nimmt Bestellungen entgegen.",
                "meta_title": "KI-Bot für den Einzelhandel | SalesDesk AI",
                "meta_desc": "KI-Berater für den Handel: Produktberatung, Verfügbarkeit, Lieferinformationen und Bestellannahme rund um die Uhr.",
                "hero_title": "KI-Berater für Ihr Geschäft",
                "hero_desc": "Kunden fragen nach Verfügbarkeit und Lieferung? Der KI-Bot antwortet rund um die Uhr, hilft bei der Auswahl und nimmt Bestellungen entgegen.",
            },
        },
    },

    "pricing": {
        "meta_title": "SalesDesk AI Preise | Schlüsselfertige KI-Bot-Implementierung",
        "meta_desc": "Wählen Sie das Format Ihrer Implementierung: Demo, schlüsselfertige Einrichtung oder Selbsttest. Klare Pakete für Ihr Unternehmen.",
        "title": "Wählen Sie Ihr Implementierungsformat",
        "desc": "Selbsttest oder schlüsselfertige Implementierung — wählen Sie den Ansatz, der zu Ihrem Unternehmen passt.",
        "intro": "Wählen Sie Ihr Format: Selbsttest oder schlüsselfertige Implementierung.",

        "packages": [
            {
                "id": "lite",
                "name": "Lite",
                "subtitle": "Go-Live in 24–48 Stunden",
                "price": "ab 149 €",
                "price_note": "einmalige Einrichtung",
                "features": [
                    "Basis-Vertriebsszenario",
                    "Wissensbasis (FAQ, Leistungen, Preise)",
                    "Test vor Go-Live",
                    "Anbindung an 1 Kanal",
                    "3 Tage Support nach Go-Live",
                    "Transparenter Launch-Prozess",
                ],
                "cta": "Implementierung besprechen",
                "cta_type": "contact",
                "popular": False,
            },
            {
                "id": "pro",
                "name": "Pro",
                "subtitle": "Multikanal + Follow-up",
                "price": "ab 349 €",
                "price_note": "einmalige Einrichtung",
                "features": [
                    "Alles aus Lite +",
                    "Lead-Segmentierung nach Anfragetyp",
                    "Follow-up-Sequenzen",
                    "Verschiedene Szenario-Pfade",
                    "Anbindung an bis zu 3 Kanäle",
                    "Reporting und Analyse",
                    "14 Tage Support und Optimierung",
                ],
                "cta": "Implementierung besprechen",
                "cta_type": "contact",
                "popular": True,
                "popular_label": "Empfohlen",
            },
            {
                "id": "max",
                "name": "Max / Enterprise",
                "subtitle": "Vollständige Integration",
                "price": "Auf Anfrage",
                "price_note": "individuell",
                "features": [
                    "Alles aus Pro +",
                    "CRM / Google Sheets Integration",
                    "Komplexe bedingte Szenarien",
                    "Team-Schulung",
                    "SLA und Prioritäts-Support",
                    "30 Tage Begleitung",
                    "Dedizierter Projektmanager",
                ],
                "cta": "Implementierung besprechen",
                "cta_type": "contact",
                "popular": False,
            },
        ],

        "self_serve": {
            "id": "self-serve",
            "name": "Self-Serve",
            "title": "Ich möchte es selbst ausprobieren",
            "subtitle": "Richten Sie den Bot selbst nach unserer Checkliste ein — für alle, die zuerst selbst anfassen wollen.",
            "features": [
                "Selbstregistrierung auf der Plattform",
                "Start-Checkliste von SalesDesk AI",
                "Szenario-Vorlagen für Ihre Branche",
                "Mini-Guide: Optimale Bot-Konfiguration",
            ],
            "cta": "Selbst ausprobieren",
        },

        "note": "NextBot-Plattformgebühren werden separat berechnet. Aktuelle Plattformpreise bei der Registrierung.",
        "faq_title": "Fragen zu den Preisen",
        "faq": [
            {"q": "Was ist in der schlüsselfertigen Implementierung enthalten?", "a": "Konfiguration der Szenarien für Ihre Branche, Aufbau der Wissensbasis (FAQ, Leistungen, Preise), Anbindung an die gewählten Kanäle und Tests vor dem Go-Live. In Pro und Max zusätzlich Segmentierung, Follow-up und Integrationen."},
            {"q": "Kann ich mit einer Demo starten?", "a": "Ja. Zuerst zeigen wir eine Demo und ein Szenario-Beispiel für Ihre Branche. Danach entscheiden Sie, welches Format passt — oder Sie starten mit dem Selbsttest."},
            {"q": "Wer erstellt die Antwortszenarien?", "a": "Die Szenarien erstellt unser Team auf Basis Ihres Briefings und Ihrer Materialien (FAQ, Preisliste, Leistungsbeschreibung). Wichtige Verzweigungen stimmen wir vor dem Go-Live mit Ihnen ab und testen alle Pfade."},
            {"q": "Was passiert nach der Anfrage?", "a": "Wir melden uns innerhalb eines Werktags, besprechen die Aufgabe, schicken ein kurzes Briefing und schlagen das passende Format vor. Anschließend Einrichtung, Test und Go-Live."},
            {"q": "Kann ich Telegram / Instagram / WhatsApp anbinden?", "a": "Ja. Telegram, WhatsApp, Instagram Direct und Website-Widget sind die Hauptkanäle. Der konkrete Umfang hängt vom gewählten Paket und den technischen Anbindungsbedingungen jeder Plattform ab."},
        ],
    },

    "demo": {
        "meta_title": "Demo des KI-Bots für Unternehmen | SalesDesk AI",
        "meta_desc": "Sehen Sie, wie der KI-Bot Kunden antwortet, Kontaktdaten erfasst und die Anfrage an Ihr Team übergibt. Wählen Sie ein Szenario für Ihre Branche.",
        "title": "So arbeitet der KI-Bot",
        "desc": "Wählen Sie ein Szenario für Ihre Branche — wir zeigen einen kurzen Dialog: von der Kundenfrage bis zum qualifizierten Lead in Ihrem Team.",
        "scenarios_title": "Szenario wählen",
        "scenarios": [
            {
                "id": "salon",
                "label": "Salon",
                "icon": "sparkles",
                "messages": [
                    {"role": "user", "text": "Hallo! Was kostet eine Maniküre und gibt es heute noch freie Termine?"},
                    {"role": "bot", "text": "Hallo! Maniküre ab 35 €. Heute sind ab 15:00 Uhr Plätze frei. Welche Uhrzeit passt Ihnen?"},
                    {"role": "user", "text": "16:00, gerne mit Lack"},
                    {"role": "bot", "text": "Notiert: 16:00, Maniküre mit Lack. Auf welchen Namen darf ich buchen und über welchen Kanal melden wir uns?"},
                    {"role": "user", "text": "Anna, Telegram"},
                    {"role": "bot", "text": "Danke, Anna. Ich übergebe die Anfrage an die Rezeption — sie bestätigt den Termin und schickt eine Erinnerung."},
                ],
                "status_final": "Lead an Rezeption übergeben",
            },
            {
                "id": "clinic",
                "label": "Klinik",
                "icon": "heart-pulse",
                "messages": [
                    {"role": "user", "text": "Ich möchte einen Termin beim Hausarzt — was kostet die Erstuntersuchung?"},
                    {"role": "bot", "text": "Die Erstuntersuchung kostet 90 €. Haben Sie einen bevorzugten Tag?"},
                    {"role": "user", "text": "Morgen vormittag"},
                    {"role": "bot", "text": "Morgen sind 09:00, 10:30 und 11:15 verfügbar. Welche Uhrzeit passt? Und auf welchen Namen darf ich den Termin buchen?"},
                    {"role": "user", "text": "10:30, Igor"},
                    {"role": "bot", "text": "Notiert, Igor. Ich übergebe an die Rezeption — sie bestätigt den Termin und schickt 2 Stunden vorher eine Erinnerung."},
                ],
                "status_final": "Lead an Rezeption übergeben",
            },
            {
                "id": "shop",
                "label": "Shop",
                "icon": "shopping-bag",
                "messages": [
                    {"role": "user", "text": "Haben Sie den Kühlschrank Samsung RB37 auf Lager? Wann können Sie liefern?"},
                    {"role": "bot", "text": "Ja, Samsung RB37 ist verfügbar. Lieferung in der Stadt am nächsten Tag. Welcher Stadtteil?"},
                    {"role": "user", "text": "Charlottenburg"},
                    {"role": "bot", "text": "Charlottenburg — Lieferung morgen bis 18:00. Preis 749 €. Sollen wir die Bestellung aufnehmen? Bitte Name und Telefonnummer."},
                    {"role": "user", "text": "Daniel, +49 30 123 4567"},
                    {"role": "bot", "text": "Notiert, Daniel. Ich übergebe an unser Vertriebsteam — es bestätigt Verfügbarkeit, Preis und Lieferzeit."},
                ],
                "status_final": "Lead an Vertriebsteam übergeben",
            },
            {
                "id": "services",
                "label": "Dienstleistungen",
                "icon": "briefcase",
                "messages": [
                    {"role": "user", "text": "Hallo, ich brauche eine juristische Beratung zu einem Vertrag"},
                    {"role": "bot", "text": "Hallo! Gerne. Geht es um einen Unternehmens- oder Privatvertrag? Wie dringend benötigen Sie die Beratung?"},
                    {"role": "user", "text": "Unternehmensvertrag, möglichst heute oder morgen"},
                    {"role": "bot", "text": "Verstanden. Heute 17:00 Uhr (online) oder morgen 11:00 Uhr (Büro) sind frei. Welches Format passt? Und Ihr Name?"},
                    {"role": "user", "text": "Morgen 11 im Büro, Alex"},
                    {"role": "bot", "text": "Danke, Alex. Ich übergebe an unsere Anwälte — sie bestätigen den Termin und schicken die Adresse."},
                ],
                "status_final": "Lead an Fachanwalt übergeben",
            },
        ],
        "status_new": "Neue Anfrage",
        "status_qualified": "Lead qualifiziert",
        "after_demo_title": "Möchten Sie ein solches Szenario für Ihre Branche?",
        "after_demo_desc": "Wir bauen einen passenden Dialog für Ihr Geschäft und zeigen ihn auf der Demo.",
        "after_demo_cta": "Solches Szenario anfragen",
        "after_demo_telegram": "Per Telegram schreiben",
        "tips_title": "Was bei der Demo wichtig ist",
        "tips": [
            "Dies ist eine kurze Illustration der Bot-Logik — kein realer Chat mit dem Unternehmen.",
            "Im Live-Bot wird das Szenario auf Ihre Leistungen, Preise und Kanäle zugeschnitten.",
            "Komplexe Anfragen übergibt die KI inklusive Kontext an einen Mitarbeiter.",
            "Im Demo-Termin zeigen wir einen echten Bot, eingerichtet für Ihre Branche.",
        ],
        "faq_title": "Fragen zur Demo",
        "faq": [
            {"q": "Ist das ein echter KI-Bot?", "a": "Auf der Seite sehen Sie eine kurze visuelle Illustration der Logik. Im Demo-Termin zeigen wir einen funktionierenden Bot auf der NextBot-Plattform, eingerichtet für die Branche des Kunden."},
            {"q": "Kann ich so einen Bot für mein Unternehmen bekommen?", "a": "Selbstverständlich. Hinterlassen Sie eine Anfrage oder schreiben Sie uns auf Telegram — wir bauen ein Szenario für Ihre Branche und zeigen es in einem kurzen Termin."},
            {"q": "Werden meine Daten in dieser Demo gespeichert?", "a": "Nein. Es ist eine statische Demonstration ohne Datenspeicherung. Bitte geben Sie keine echten personenbezogenen Daten ein."},
        ],
    },

    "about": {
        "meta_title": "Über SalesDesk AI | KI-Vertriebslösungen Integrator",
        "meta_desc": "SalesDesk AI — Ihr Integrator für KI-Vertriebslösungen. Wir richten KI-Bots für Ihr Geschäft in 24–48 Stunden ein.",
        "title": "Über SalesDesk AI",
        "intro": "Wir sind das Team von SalesDesk AI — Ihr Integrator für KI-gestützte Automatisierung von Anfragen und Kundendialogen. Wir helfen kleinen und mittleren Unternehmen, KI-Vertriebsassistenten schnell und zuverlässig zu implementieren.",
        "mission_title": "Unsere Mission",
        "mission": "KI-Vertrieb für den Mittelstand zugänglich machen. Keine IT-Abteilung nötig — wir richten alles schlüsselfertig ein.",
        "principles_title": "Unsere Prinzipien",
        "principles": [
            {"title": "Geschwindigkeit", "desc": "Go-Live in 24–48 Stunden statt Monaten. Sie generieren schnell warme Leads."},
            {"title": "Transparenz", "desc": "Klare Preise, klarer Prozess. Keine versteckten Kosten."},
            {"title": "Branchen-Szenarien", "desc": "Kein universeller Bot — sondern Antworten und Logik genau für Ihr Geschäft."},
            {"title": "Begleitung", "desc": "Wir lassen Sie nach der Einrichtung nicht allein. Optimierung und Skalierung inklusive."},
        ],
        "how_title": "So arbeiten wir",
        "how_steps": [
            {"num": "01", "title": "Briefing", "desc": "Kurzer Termin (20–30 Minuten): Branche, Leistungen, häufige Kundenfragen und Kanäle."},
            {"num": "02", "title": "Szenarien", "desc": "Wir bauen die Dialog-Logik für Ihre Branche, laden die Wissensbasis und testen alle Pfade."},
            {"num": "03", "title": "Go-Live & Begleitung", "desc": "Wir binden den Bot an Ihre Kanäle an, schulen das Team und begleiten nach dem Launch."},
        ],
        "tech_title": "Technologie",
        "tech_desc": "SalesDesk AI basiert auf der NextBot-Plattform — einer modernen KI-Plattform für intelligente Vertriebsbots. Als offizieller Integrator helfen wir Unternehmen, das volle Potenzial der Plattform zu nutzen.",
    },

    "contact": {
        "meta_title": "SalesDesk AI Kontakt | Nehmen Sie Kontakt auf",
        "meta_desc": "Kontaktieren Sie SalesDesk AI: Telegram, E-Mail, Kontaktformular. Wir zeigen eine Demo und ein Szenario für Ihre Branche.",
        "title": "Kontakt aufnehmen",
        "desc": "Beschreiben Sie kurz Ihr Geschäft — wir zeigen eine Demo und ein Szenario für Ihre Branche.",
        "form_title": "Demo anfordern",
        "form_micro": "Wir antworten und zeigen, wie der KI-Bot in Ihrer Branche arbeiten kann.",
        "form_name": "Ihr Name",
        "form_contact": "Telegram, Telefon oder E-Mail",
        "form_business": "Geschäftstyp",
        "form_message": "Beschreiben Sie kurz Ihre Anforderung",
        "form_message_toggle": "Nachricht hinzufügen",
        "form_submit": "Demo anfordern",
        "form_success": "Anfrage gesendet. Wir melden uns in Kürze und zeigen ein Szenario für Ihre Branche.",
        "form_error": "Sendefehler. Bitte versuchen Sie es erneut oder kontaktieren Sie uns per Telegram.",
        "trust_badges": [
            "Kein Spam",
            "Daten nicht an Dritte",
            "Start mit Demo möglich",
        ],
        "telegram_title": "Oder schreiben Sie uns in Telegram",
        "telegram_desc": "Der schnellste Weg, eine Frage zu stellen oder Ihre Implementierung zu besprechen",
    },

    "privacy": {
        "meta_title": "Datenschutzerklärung | SalesDesk AI",
        "meta_desc": "Datenschutzerklärung von SalesDesk AI. Erfahren Sie, wie wir Ihre personenbezogenen Daten verarbeiten und schützen.",
        "title": "Datenschutzerklärung",
        "updated": "Letzte Aktualisierung: Januar 2026",
        "sections": [
            {"title": "Welche Daten wir erheben", "text": "Bei Nutzung unserer Website und Kontaktformulare können wir folgende Daten erheben: Name, Telefonnummer oder Telegram-Handle, Geschäftstyp und Anforderungsbeschreibung. Ohne Ihre Einwilligung erheben wir keine Daten automatisch."},
            {"title": "Verwendung der Daten", "text": "Die erhobenen Daten verwenden wir ausschließlich zur Kontaktaufnahme bezüglich Ihrer Anfrage, zur Empfehlung der optimalen Lösung und zur Verbesserung unseres Services."},
            {"title": "Analytik und Cookies", "text": "Auf unserer Website können Analysedienste (Google Analytics, Meta Pixel) zur Besucheranalyse eingesetzt werden. Diese Dienste verwenden Cookies. Sie können Cookies über den Einwilligungsbanner ablehnen. Ohne Ihre Zustimmung werden keine Analyse-Cookies gesetzt."},
            {"title": "Weitergabe an Dritte", "text": "Wir verkaufen oder übermitteln Ihre personenbezogenen Daten nicht an Dritte, außer in gesetzlich vorgeschriebenen Fällen."},
            {"title": "Datenspeicherung", "text": "Daten werden auf gesicherten Servern gespeichert. Wir treffen angemessene Maßnahmen zum Schutz vor unbefugtem Zugriff."},
            {"title": "Ihre Rechte", "text": "Sie können die Löschung Ihrer Daten beantragen, indem Sie uns über das Kontaktformular oder Telegram kontaktieren. Gemäß DSGVO haben Sie das Recht auf Auskunft, Berichtigung und Löschung Ihrer Daten."},
        ],
    },

    "terms": {
        "meta_title": "AGB | SalesDesk AI",
        "meta_desc": "Allgemeine Geschäftsbedingungen für die Nutzung der SalesDesk AI Website und Services.",
        "title": "Allgemeine Geschäftsbedingungen",
        "updated": "Letzte Aktualisierung: Januar 2026",
        "sections": [
            {"title": "Allgemeines", "text": "Diese AGB regeln die Nutzung der SalesDesk AI Website. Durch die Nutzung stimmen Sie diesen Bedingungen zu."},
            {"title": "Leistungen", "text": "SalesDesk AI bietet Einrichtungs- und Implementierungsservices für KI-Vertriebsbots auf Basis der NextBot-Plattform. Der genaue Leistungsumfang richtet sich nach dem gewählten Paket."},
            {"title": "Garantien", "text": "SalesDesk AI führt die Arbeiten im vereinbarten Zeitrahmen durch, sofern der Kunde alle erforderlichen Materialien bereitstellt. Wir garantieren keine konkreten finanziellen Ergebnisse."},
            {"title": "Zahlung", "text": "Die Zahlung für SalesDesk AI Services erfolgt gemäß dem gewählten Paket. Das NextBot-Plattformabonnement wird separat gemäß den Plattformtarifen berechnet."},
            {"title": "Haftung", "text": "SalesDesk AI haftet nicht für den Betrieb der NextBot-Plattform, Ausfälle von Messenger-Diensten und Drittanbietern."},
        ],
    },

    "blog": {
        "meta_title": "SalesDesk AI Blog | Artikel über KI-Vertrieb",
        "meta_desc": "Nützliche Artikel über Vertriebsautomatisierung, KI-Bots und digitales Marketing. Tipps, Referenzen und Anleitungen vom SalesDesk AI Team.",
        "title": "Blog",
        "desc": "Artikel über Vertriebsautomatisierung und KI-Technologien",
        "read_also": "Lesen Sie auch",
        "next_step": "Nächster Schritt: Demo des KI-Bots ansehen",
        "categories": {
            "automation": "Automatisierung",
            "cases": "Referenzen",
            "guides": "Anleitungen",
            "trends": "Trends",
        },
    },

    "cases": {
        "meta_title": "SalesDesk AI Referenzen | KI-Bot Implementierungsbeispiele",
        "meta_desc": "Szenarien für KI-Bot-Implementierungen in verschiedenen Branchen: Salons, Kurse, Kliniken, Werkstätten.",
        "title": "Szenarien & Vorgehen",
        "desc": "Wie SalesDesk AI in verschiedenen Branchen arbeitet",
        "coming_soon": "Dieser Bereich entsteht gerade. Wir bereiten Beispiele aus verschiedenen Branchen vor — im Demo-Termin zeigen wir Vorgehen und Logik passend zu Ihrem Geschäft.",
    },

    "breadcrumbs": {
        "home": "Startseite",
        "solutions": "Lösungen",
        "pricing": "Preise",
        "demo": "Demo",
        "blog": "Blog",
        "cases": "Referenzen",
        "about": "Über uns",
        "contact": "Kontakt",
        "privacy": "Datenschutz",
        "terms": "AGB",
    },

    "consent": {
        "text": "Wir verwenden Cookies für Analysezwecke. Gemäß DSGVO benötigen wir Ihre Zustimmung.",
        "accept": "Akzeptieren",
        "decline": "Ablehnen",
    },

    "not_found": {
        "title": "Seite nicht gefunden",
        "desc": "Die Seite wurde möglicherweise verschoben oder gelöscht.",
        "cta": "Zur Startseite",
    },
}
