CONTENT_DE = {
    "lang": "de",
    "lang_code": "de",
    "lang_name": "DE",
    "other_lang": "ru",
    "other_lang_name": "RU",

    "brand": "SalesDesk AI",
    "brand_tagline": "KI-Sales-Bot 24/7",
    "brand_full": "SalesDesk AI — KI-Sales-Bot 24/7",

    "nav": {
        "home": "Startseite",
        "solutions": "Loesungen",
        "pricing": "Preise",
        "demo": "Demo",
        "blog": "Blog",
        "cases": "Referenzen",
        "about": "Ueber uns",
        "contact": "Kontakt",
    },

    "cta": {
        "try_demo": "Demo testen",
        "turnkey": "Komplettloesung anfragen",
        "telegram": "Telegram kontaktieren",
        "self_serve": "Selbst einrichten",
        "contact_us": "Kontakt aufnehmen",
        "read_more": "Mehr erfahren",
        "all_solutions": "Alle Loesungen",
        "back_to_blog": "Zurueck zum Blog",
    },

    "footer": {
        "description": "KI-Vertriebsassistent, der rund um die Uhr Kundenanfragen beantwortet, Leads qualifiziert und an Ihr Vertriebsteam uebergibt.",
        "nav_title": "Navigation",
        "legal_title": "Rechtliches",
        "contact_title": "Kontakt",
        "privacy": "Datenschutz",
        "terms": "AGB",
        "copyright": "SalesDesk AI. Alle Rechte vorbehalten.",
        "powered_by": "Technologie-Basis: NextBot",
    },

    "home": {
        "meta_title": "SalesDesk AI — KI-Sales-Bot 24/7 | Vertriebsautomatisierung",
        "meta_desc": "KI-Vertriebsassistent 24/7: Sofortantwort, Lead-Qualifizierung, Uebergabe an Ihr Team. Implementierung in 24-48 Stunden.",
        "hero_title": "Leads warten nicht",
        "hero_highlight": "SalesDesk AI antwortet sofort",
        "hero_desc": "Ihr KI-Vertriebsassistent arbeitet rund um die Uhr: beantwortet Anfragen in Sekunden, qualifiziert Leads und uebergibt sie an Ihr Team. Kein Lead geht verloren.",
        "hero_cta_primary": "Demo testen",
        "hero_cta_secondary": "Komplettloesung anfragen",

        "problems_title": "Kommt Ihnen das bekannt vor?",
        "problems": [
            {"icon": "clock", "title": "Anfragen gehen verloren", "desc": "Ein Kunde schreibt um 23 Uhr — die Antwort kommt erst am naechsten Morgen. Zu spaet: Er ist beim Wettbewerb."},
            {"icon": "users", "title": "Ihr Team ist ueberlastet", "desc": "80% der Fragen wiederholen sich. Ihr Vertrieb verbringt Zeit mit FAQ statt mit Abschluessen."},
            {"icon": "trending-down", "title": "Kein Follow-up", "desc": "Interessenten fragen an und verschwinden. Niemand erinnert, klaert nach oder schliesst ab."},
        ],

        "solution_title": "So loest SalesDesk AI das",
        "solution_steps": [
            {"icon": "zap", "title": "Sofortantwort", "desc": "Der Bot antwortet in 2-3 Sekunden — zu jeder Tages- und Nachtzeit."},
            {"icon": "filter", "title": "Qualifizierung", "desc": "KI stellt gezielte Fragen, erkennt Bedarf und Budget. Ihr Team erhaelt qualifizierte Leads."},
            {"icon": "repeat", "title": "Follow-up", "desc": "Automatische Erinnerungen und Follow-up-Sequenzen. Kein Interessent wird vergessen."},
            {"icon": "user-check", "title": "Uebergabe ans Team", "desc": "Wenn der Lead bereit ist — uebergibt der Bot das Gespraech mit vollem Kontext an Ihr Team."},
        ],

        "industries_title": "Fuer Ihre Branche optimiert",
        "industries_desc": "SalesDesk AI passt sich an die Anforderungen Ihres Geschaefts an",

        "stats_title": "Warum Unternehmen auf KI-Vertrieb setzen",
        "stats": [
            {"value": "24/7", "label": "Verfuegbarkeit"},
            {"value": "2-3 Sek", "label": "Antwortzeit"},
            {"value": "24-48h", "label": "Implementierung"},
            {"value": "0", "label": "Verlorene Leads"},
        ],

        "process_title": "Start in 3 Schritten",
        "process_steps": [
            {"num": "01", "title": "Briefing", "desc": "Beschreiben Sie Ihr Geschaeft, Ihre Leistungen und typische Kundenanfragen."},
            {"num": "02", "title": "Einrichtung", "desc": "Wir erstellen Szenarien, laden Ihre Wissensbasis und testen alles gruendlich."},
            {"num": "03", "title": "Go-Live", "desc": "Anbindung an Ihre Kanaele und Schulung Ihres Teams."},
        ],

        "guarantee_title": "Prozessgarantie",
        "guarantee_desc": "Wir garantieren die Implementierung Ihres KI-Bots innerhalb von 24-48 Stunden nach Bereitstellung aller Materialien. Schaffen wir es nicht — erstatten wir die Einrichtungsgebuehr.",

        "faq_title": "Haeufige Fragen",
        "faq": [
            {"q": "Was ist SalesDesk AI?", "a": "SalesDesk AI ist ein KI-Vertriebsassistent, der rund um die Uhr arbeitet. Er beantwortet Kundenanfragen, qualifiziert Leads und uebergibt sie an Ihr Vertriebsteam. Technologische Basis ist die NextBot-Plattform."},
            {"q": "Wie schnell kann ich starten?", "a": "Mit dem Komplettpaket in 24-48 Stunden ab Bereitstellung Ihrer Materialien (FAQ, Preisliste, Leistungsbeschreibung). Selbsteinrichtung ab 10 Minuten."},
            {"q": "Ersetzt der Bot meinen Vertrieb?", "a": "Nein. Der Bot uebernimmt Routineaufgaben: Erstantworten, Qualifizierung, FAQ. Ihr Team erhaelt vorqualifizierte Leads und konzentriert sich auf Abschluesse."},
            {"q": "Welche Kanaele werden unterstuetzt?", "a": "Telegram, WhatsApp, Instagram Direct, Website-Widget, Facebook Messenger — abhaengig vom gewaehlten Paket."},
            {"q": "Was passiert bei falschen Antworten?", "a": "Der Bot arbeitet ausschliesslich mit Ihrer Wissensbasis. Bei unklaren Anfragen leitet er an einen Mitarbeiter weiter. Vor dem Start testen wir alle Szenarien."},
            {"q": "Was kostet es?", "a": "Es gibt 4 Pakete: von der Selbsteinrichtung (kostenfrei unsererseits) bis zur vollstaendigen CRM-Integration. Details auf der Preisseite."},
        ],
    },

    "solutions": {
        "meta_title": "SalesDesk AI Loesungen nach Branche | KI-Bot fuer Ihr Geschaeft",
        "meta_desc": "KI-Sales-Bot fuer Kosmetik, Bildung, Kliniken, Autowerkstaetten, Gastronomie, Immobilien und Einzelhandel. Einrichtung in 24-48 Stunden.",
        "title": "Loesungen fuer Ihre Branche",
        "desc": "SalesDesk AI passt sich an Ihre Branche an. Waehlen Sie Ihren Bereich — wir zeigen, wie der KI-Bot bei Ihnen arbeitet.",
        "items": {
            "beauty": {
                "name": "Kosmetik & Salons",
                "icon": "sparkles",
                "short_desc": "KI-Bot fuer Schoenheitssalons, Kosmetikstudios und Barbershops",
                "meta_title": "KI-Bot fuer Schoenheitssalons | SalesDesk AI",
                "meta_desc": "Automatisieren Sie Terminbuchungen und Beratungen in Ihrem Salon. KI-Bot antwortet 24/7, bucht Termine und erinnert an Besuche.",
                "hero_title": "KI-Rezeption fuer Ihren Salon",
                "hero_desc": "Kunden schreiben ausserhalb der Oeffnungszeiten? Ihre Rezeption kommt nicht hinterher? SalesDesk AI arbeitet rund um die Uhr: beraet zu Leistungen und Preisen, bucht Termine und erinnert an Besuche.",
                "problems": [
                    "Kunden schreiben um 22 Uhr — die Antwort kommt erst am naechsten Morgen",
                    "Die Rezeption ist mit Telefonaten ueberlastet und kann nicht auf Messenger antworten",
                    "Keine automatischen Erinnerungen — Kunden vergessen Termine",
                    "Neukunden erhalten keine Beratung zu Leistungen und gehen woanders hin",
                ],
                "how_it_works": [
                    {"title": "Leistungsberatung", "desc": "Der Bot kennt alle Preise, Behandlungsbeschreibungen und Kontraindikationen. Antwortet sofort auf alle Fragen."},
                    {"title": "Online-Terminbuchung", "desc": "Kunden waehlen Behandlung, Mitarbeiter und Wunschtermin direkt im Chat."},
                    {"title": "Erinnerungen", "desc": "Automatische Erinnerung einen Tag und eine Stunde vor dem Termin. Reduziert No-Shows."},
                    {"title": "Uebergabe an Mitarbeiter", "desc": "Komplexe Fragen (Allergien, individuelle Behandlungen) werden sofort an die Rezeption weitergeleitet."},
                ],
                "result_title": "Ergebnis",
                "results": [
                    "Keine Anfrage geht verloren — auch nachts nicht",
                    "Rezeption konzentriert sich auf Kunden vor Ort statt auf Chats",
                    "Weniger No-Shows durch automatische Erinnerungen",
                    "Mehr Buchungen ueber Messenger und Social Media",
                ],
            },
            "education": {
                "name": "Bildung & Kurse",
                "icon": "graduation-cap",
                "short_desc": "KI-Bot fuer Online-Schulen, Kurse und Bildungszentren",
                "meta_title": "KI-Bot fuer Bildung und Kurse | SalesDesk AI",
                "meta_desc": "Automatisieren Sie die Bearbeitung von Kursanfragen. KI-Bot beraet zu Programmen, beantwortet Fragen und nimmt Anmeldungen entgegen — 24/7.",
                "hero_title": "KI-Assistent fuer Ihr Bildungsgeschaeft",
                "hero_desc": "Interessenten stellen immer die gleichen Fragen: Programm, Dauer, Kosten, Format. SalesDesk AI uebernimmt das — antwortet sofort, hilft bei der Kurswahl und fuehrt zur Anmeldung.",
                "problems": [
                    "Berater beantworten hundertmal taeglich die gleichen Fragen",
                    "Anfragen von Website und Social Media werden zu langsam bearbeitet",
                    "Kein Follow-up: Interessent fragt nach einem Kurs und verschwindet",
                    "In der Anmeldesaison ist das Team voellig ueberlastet",
                ],
                "how_it_works": [
                    {"title": "Programmberatung", "desc": "Der Bot kennt alle Kurse, Zeitplaene, Preise und Formate. Hilft bei der passenden Auswahl."},
                    {"title": "Qualifizierung", "desc": "Ermittelt Vorkenntnisse, Lernziele und Budget. Empfiehlt die optimale Option."},
                    {"title": "Follow-up", "desc": "Wenn sich der Interessent nicht sofort anmeldet, erinnert der Bot und beantwortet weitere Fragen."},
                    {"title": "Anmeldung", "desc": "Fuehrt zur Kursanmeldung und kann einen Zahlungslink senden."},
                ],
                "result_title": "Ergebnis",
                "results": [
                    "Antwortzeit: Sekunden statt Stunden",
                    "Berater konzentrieren sich auf Verkaeufe statt FAQ",
                    "Hoehere Konversion von Anfrage zu Anmeldung durch Follow-up",
                    "Skalierung ohne zusaetzliche Mitarbeiter",
                ],
            },
            "clinic": {
                "name": "Kliniken & Zahnaerzte",
                "icon": "heart-pulse",
                "short_desc": "KI-Bot fuer medizinische Kliniken und Zahnarztpraxen",
                "meta_title": "KI-Bot fuer Kliniken und Zahnaerzte | SalesDesk AI",
                "meta_desc": "KI-Assistent fuer medizinische Einrichtungen: Terminbuchung, Leistungsberatung, Patientenerinnerungen. Rund um die Uhr verfuegbar.",
            },
            "auto": {
                "name": "Autowerkstatt & Teilehandel",
                "icon": "car",
                "short_desc": "KI-Bot fuer Autowerkstaetten und Ersatzteilhaendler",
                "meta_title": "KI-Bot fuer Autowerkstaetten | SalesDesk AI",
                "meta_desc": "Automatisieren Sie Auftragsannahme in der Werkstatt. KI-Bot beraet zu Leistungen, nimmt Termine an und antwortet 24/7.",
            },
            "food": {
                "name": "Gastronomie & Lieferservice",
                "icon": "utensils",
                "short_desc": "KI-Bot fuer Restaurants, Cafes und Lieferdienste",
                "meta_title": "KI-Bot fuer Gastronomie | SalesDesk AI",
                "meta_desc": "KI-Assistent fuer die Gastronomie: Tischreservierung, Speisekarte, Bestellungen. Automatisierung des Bestellprozesses 24/7.",
            },
            "real-estate": {
                "name": "Immobilien & Renovierung",
                "icon": "building",
                "short_desc": "KI-Bot fuer Immobilienagenturen und Renovierungsfirmen",
                "meta_title": "KI-Bot fuer Immobilien | SalesDesk AI",
                "meta_desc": "Automatisieren Sie die Bearbeitung von Immobilienanfragen. KI-Bot qualifiziert Kaeufer, schlaegt Objekte vor und bucht Besichtigungen.",
            },
            "retail": {
                "name": "Einzelhandel & Technik",
                "icon": "shopping-bag",
                "short_desc": "KI-Bot fuer Moebel-, Technik- und Einzelhandelsgeschaefte",
                "meta_title": "KI-Bot fuer den Einzelhandel | SalesDesk AI",
                "meta_desc": "KI-Berater fuer den Handel: Produktberatung, Verfuegbarkeit, Lieferinformationen und Bestellannahme rund um die Uhr.",
            },
        },
    },

    "pricing": {
        "meta_title": "SalesDesk AI Preise | KI-Bot Implementierungspakete",
        "meta_desc": "4 Implementierungspakete fuer Ihren KI-Sales-Bot: von der Selbsteinrichtung bis zur vollstaendigen CRM-Integration.",
        "title": "Waehlen Sie Ihr Paket",
        "desc": "Von der Selbsteinrichtung bis zur Komplettimplementierung mit CRM-Anbindung",
        "packages": [
            {
                "id": "self-serve",
                "name": "Self-Serve",
                "subtitle": "In 10 Minuten selbst einrichten",
                "price": "Kostenfrei",
                "price_note": "unsererseits",
                "features": [
                    "Selbstregistrierung auf der Plattform",
                    "Start-Checkliste von SalesDesk AI",
                    "Szenario-Vorlagen fuer Ihre Branche",
                    "Mini-Guide: Optimale Bot-Konfiguration",
                    "Zugang zur Wissensbasis und FAQ",
                ],
                "cta": "Kostenlos einrichten",
                "cta_type": "referral",
                "popular": False,
            },
            {
                "id": "lite",
                "name": "Lite",
                "subtitle": "Go-Live in 24-48 Stunden",
                "price": "ab 149 EUR",
                "price_note": "einmalige Einrichtung",
                "features": [
                    "Basis-Vertriebsszenario",
                    "Wissensbasis (FAQ, Leistungen, Preise)",
                    "Test vor Go-Live",
                    "Anbindung an 1 Kanal",
                    "3 Tage Support nach Go-Live",
                    "Garantie: Go-Live oder Geld zurueck",
                ],
                "cta": "Einrichtung bestellen",
                "cta_type": "contact",
                "popular": False,
            },
            {
                "id": "pro",
                "name": "Pro",
                "subtitle": "Multikanal + Follow-up",
                "price": "ab 349 EUR",
                "price_note": "einmalige Einrichtung",
                "features": [
                    "Alles aus Lite +",
                    "Lead-Segmentierung nach Anfragetyp",
                    "Follow-up-Sequenzen",
                    "Verschiedene Szenario-Pfade",
                    "Anbindung an bis zu 3 Kanaele",
                    "Reporting und Analyse",
                    "14 Tage Support und Optimierung",
                ],
                "cta": "Pro waehlen",
                "cta_type": "contact",
                "popular": True,
            },
            {
                "id": "max",
                "name": "Max / Enterprise",
                "subtitle": "Vollstaendige Integration",
                "price": "Auf Anfrage",
                "price_note": "individuell",
                "features": [
                    "Alles aus Pro +",
                    "CRM / Google Sheets Integration",
                    "Komplexe bedingte Szenarien",
                    "Team-Schulung",
                    "SLA und Prioritaets-Support",
                    "30 Tage Begleitung",
                    "Dedizierter Projektmanager",
                ],
                "cta": "Projekt besprechen",
                "cta_type": "contact",
                "popular": False,
            },
        ],
        "note": "NextBot-Plattformgebuehren werden separat berechnet. Aktuelle Plattformpreise bei der Registrierung.",
        "faq_title": "Fragen zu den Preisen",
        "faq": [
            {"q": "Was ist im Paketpreis enthalten?", "a": "Die Paketpreise von SalesDesk AI sind einmalige Gebuehren fuer Einrichtung und Implementierung. Das NextBot-Plattformabonnement wird separat nach den Plattformtarifen berechnet."},
            {"q": "Kann ich das Paket wechseln?", "a": "Ja, Sie koennen jederzeit auf ein hoeherwertiges Paket upgraden und zahlen nur die Differenz."},
            {"q": "Was bedeutet Prozessgarantie?", "a": "Wir garantieren den Bot-Launch im vereinbarten Zeitrahmen, sofern Sie alle erforderlichen Materialien bereitstellen. Schaffen wir es nicht, erstatten wir die Einrichtungsgebuehr."},
        ],
    },

    "demo": {
        "meta_title": "SalesDesk AI Demo | KI-Sales-Bot testen",
        "meta_desc": "Testen Sie den KI-Vertriebsassistenten direkt auf unserer Website. Sehen Sie, wie der Bot Fragen beantwortet und Leads qualifiziert.",
        "title": "Testen Sie SalesDesk AI",
        "desc": "Probieren Sie den KI-Bot live aus. Stellen Sie Fragen wie ein echter Kunde — und erleben Sie, wie der Bot antwortet und qualifiziert.",
        "widget_title": "Demo-Widget",
        "widget_fallback": "Falls das Widget nicht laedt — testen Sie den Bot in Telegram",
        "tips_title": "So testen Sie richtig",
        "tips": [
            "Fragen Sie nach Leistungen und Preisen — wie ein echter Kunde",
            "Stellen Sie eine themenfremde Frage — sehen Sie, wie der Bot reagiert",
            "Stellen Sie eine Nachfrage — bewerten Sie die Antworttiefe",
            "Bitten Sie um Verbindung mit einem Mitarbeiter — pruefen Sie die Uebergabe",
        ],
        "faq_title": "Fragen zur Demo",
        "faq": [
            {"q": "Ist das ein echter KI-Bot?", "a": "Ja, ein funktionierender Bot auf der NextBot-Plattform, konfiguriert als Demo fuer SalesDesk AI."},
            {"q": "Kann ich so einen Bot fuer mein Unternehmen bekommen?", "a": "Selbstverstaendlich. Waehlen Sie ein Paket auf der Preisseite oder kontaktieren Sie uns per Telegram."},
            {"q": "Werden meine Demo-Daten gespeichert?", "a": "Die Demo dient nur zum Testen. Bitte geben Sie keine echten personenbezogenen Daten ein."},
        ],
    },

    "about": {
        "meta_title": "Ueber SalesDesk AI | KI-Vertriebsloesungen Integrator",
        "meta_desc": "SalesDesk AI — Ihr Integrator fuer KI-Vertriebsloesungen. Wir richten KI-Bots fuer Ihr Geschaeft in 24-48 Stunden ein.",
        "title": "Ueber SalesDesk AI",
        "intro": "Wir sind das Team von SalesDesk AI — Ihr Integrator fuer KI-gestuetzte Vertriebsautomatisierung. Wir helfen Unternehmen in Deutschland und Europa, KI-Vertriebsassistenten schnell und zuverlaessig zu implementieren.",
        "mission_title": "Unsere Mission",
        "mission": "KI-Vertrieb fuer den Mittelstand zugaenglich machen. Keine IT-Abteilung noetig — wir richten alles schluesselfertg ein.",
        "values": [
            {"title": "Geschwindigkeit", "desc": "Go-Live in 24-48 Stunden statt Monaten. Sie generieren sofort Leads."},
            {"title": "Transparenz", "desc": "Klare Preise, klarer Prozess. Keine versteckten Kosten."},
            {"title": "Prozessgarantie", "desc": "Wir stehen fuer Termine und Qualitaet ein. Nicht geliefert — Geld zurueck."},
            {"title": "Begleitung", "desc": "Wir lassen Sie nach der Einrichtung nicht allein. Optimierung und Skalierung inklusive."},
        ],
        "tech_title": "Technologie",
        "tech_desc": "SalesDesk AI basiert auf der NextBot-Plattform — einer modernen KI-Plattform fuer intelligente Vertriebsbots. Als offizieller Integrator helfen wir Unternehmen, das volle Potenzial der Plattform zu nutzen.",
    },

    "contact": {
        "meta_title": "SalesDesk AI Kontakt | Nehmen Sie Kontakt auf",
        "meta_desc": "Kontaktieren Sie SalesDesk AI: Telegram, E-Mail, Kontaktformular. Antwort innerhalb einer Stunde waehrend der Geschaeftszeiten.",
        "title": "Kontakt aufnehmen",
        "desc": "Beschreiben Sie Ihr Geschaeft — wir schlagen die optimale Loesung vor",
        "form_title": "Anfrage senden",
        "form_name": "Ihr Name",
        "form_phone": "Telefon oder Telegram",
        "form_business": "Geschaeftstyp",
        "form_message": "Beschreiben Sie kurz Ihre Anforderung",
        "form_submit": "Anfrage senden",
        "form_success": "Anfrage gesendet! Wir melden uns in Kuerze bei Ihnen.",
        "form_error": "Sendefehler. Bitte versuchen Sie es erneut oder kontaktieren Sie uns per Telegram.",
        "telegram_title": "Oder schreiben Sie uns in Telegram",
        "telegram_desc": "Der schnellste Weg, eine Frage zu stellen oder Ihr Projekt zu besprechen",
    },

    "privacy": {
        "meta_title": "Datenschutzerklaerung | SalesDesk AI",
        "meta_desc": "Datenschutzerklaerung von SalesDesk AI. Erfahren Sie, wie wir Ihre personenbezogenen Daten verarbeiten und schuetzen.",
        "title": "Datenschutzerklaerung",
        "updated": "Letzte Aktualisierung: Januar 2026",
        "sections": [
            {"title": "Welche Daten wir erheben", "text": "Bei Nutzung unserer Website und Kontaktformulare koennen wir folgende Daten erheben: Name, Telefonnummer oder Telegram-Handle, Geschaeftstyp und Anforderungsbeschreibung. Ohne Ihre Einwilligung erheben wir keine Daten automatisch."},
            {"title": "Verwendung der Daten", "text": "Die erhobenen Daten verwenden wir ausschliesslich zur Kontaktaufnahme bezueglich Ihrer Anfrage, zur Empfehlung der optimalen Loesung und zur Verbesserung unseres Services."},
            {"title": "Analytik und Cookies", "text": "Auf unserer Website koennen Analysedienste (Google Analytics, Meta Pixel) zur Besucheranalyse eingesetzt werden. Diese Dienste verwenden Cookies. Sie koennen Cookies ueber den Einwilligungsbanner ablehnen. Ohne Ihre Zustimmung werden keine Analyse-Cookies gesetzt."},
            {"title": "Weitergabe an Dritte", "text": "Wir verkaufen oder uebermitteln Ihre personenbezogenen Daten nicht an Dritte, ausser in gesetzlich vorgeschriebenen Faellen."},
            {"title": "Datenspeicherung", "text": "Daten werden auf gesicherten Servern gespeichert. Wir treffen angemessene Massnahmen zum Schutz vor unbefugtem Zugriff."},
            {"title": "Ihre Rechte", "text": "Sie koennen die Loeschung Ihrer Daten beantragen, indem Sie uns ueber das Kontaktformular oder Telegram kontaktieren. Gemaess DSGVO haben Sie das Recht auf Auskunft, Berichtigung und Loeschung Ihrer Daten."},
        ],
    },

    "terms": {
        "meta_title": "AGB | SalesDesk AI",
        "meta_desc": "Allgemeine Geschaeftsbedingungen fuer die Nutzung der SalesDesk AI Website und Services.",
        "title": "Allgemeine Geschaeftsbedingungen",
        "updated": "Letzte Aktualisierung: Januar 2026",
        "sections": [
            {"title": "Allgemeines", "text": "Diese AGB regeln die Nutzung der SalesDesk AI Website. Durch die Nutzung stimmen Sie diesen Bedingungen zu."},
            {"title": "Leistungen", "text": "SalesDesk AI bietet Einrichtungs- und Implementierungsservices fuer KI-Vertriebsbots auf Basis der NextBot-Plattform. Der genaue Leistungsumfang richtet sich nach dem gewaehlten Paket."},
            {"title": "Garantien", "text": "SalesDesk AI garantiert die Durchfuehrung der Arbeiten im vereinbarten Zeitrahmen, sofern der Kunde alle erforderlichen Materialien bereitstellt. Wir garantieren keine konkreten finanziellen Ergebnisse."},
            {"title": "Zahlung", "text": "Die Zahlung fuer SalesDesk AI Services erfolgt gemaess dem gewaehlten Paket. Das NextBot-Plattformabonnement wird separat nach den Plattformtarifen berechnet."},
            {"title": "Haftung", "text": "SalesDesk AI haftet nicht fuer den Betrieb der NextBot-Plattform, Ausfaelle von Messenger-Diensten und Drittanbietern."},
        ],
    },

    "blog": {
        "meta_title": "SalesDesk AI Blog | Artikel ueber KI-Vertrieb",
        "meta_desc": "Nuetzliche Artikel ueber Vertriebsautomatisierung, KI-Bots und digitales Marketing. Tipps, Referenzen und Anleitungen vom SalesDesk AI Team.",
        "title": "Blog",
        "desc": "Artikel ueber Vertriebsautomatisierung und KI-Technologien",
        "read_also": "Lesen Sie auch",
        "next_step": "Naechster Schritt: Testen Sie den KI-Bot live",
        "categories": {
            "automation": "Automatisierung",
            "cases": "Referenzen",
            "guides": "Anleitungen",
            "trends": "Trends",
        },
    },

    "cases": {
        "meta_title": "SalesDesk AI Referenzen | KI-Bot Implementierungsbeispiele",
        "meta_desc": "Praxisbeispiele fuer KI-Bot-Implementierungen. Anonymisierte Referenzen aus verschiedenen Branchen.",
        "title": "Referenzen und Szenarien",
        "desc": "Beispiele, wie SalesDesk AI in verschiedenen Branchen arbeitet",
        "coming_soon": "Dieser Bereich wird gerade erstellt. Bald finden Sie hier echte Referenzen aus verschiedenen Branchen.",
    },

    "breadcrumbs": {
        "home": "Startseite",
        "solutions": "Loesungen",
        "pricing": "Preise",
        "demo": "Demo",
        "blog": "Blog",
        "cases": "Referenzen",
        "about": "Ueber uns",
        "contact": "Kontakt",
        "privacy": "Datenschutz",
        "terms": "AGB",
    },

    "consent": {
        "text": "Wir verwenden Cookies fuer Analysezwecke. Gemaess DSGVO benoetigen wir Ihre Zustimmung.",
        "accept": "Akzeptieren",
        "decline": "Ablehnen",
    },

    "not_found": {
        "title": "Seite nicht gefunden",
        "desc": "Die Seite wurde moeglicherweise verschoben oder geloescht.",
        "cta": "Zur Startseite",
    },
}
