CONTENT_DE = {
    "lang": "de",
    "lang_code": "de",
    "lang_name": "DE",
    "other_lang": "ru",
    "other_lang_name": "RU",

    "brand": "SalesDesk AI",
    "brand_tagline": "KI-Sales-Bot 24/7",
    "brand_full": "SalesDesk AI — KI-Sales-Bot 24/7",

    "nav": {
        "home": "Startseite",
        "solutions": "Lösungen",
        "pricing": "Preise",
        "demo": "Demo",
        "blog": "Blog",
        "cases": "Referenzen",
        "about": "Über uns",
        "contact": "Kontakt",
    },

    "cta": {
        "try_demo": "Demo testen",
        "turnkey": "Komplettlösung anfragen",
        "telegram": "Telegram kontaktieren",
        "self_serve": "Selbst einrichten",
        "contact_us": "Kontakt aufnehmen",
        "read_more": "Mehr erfahren",
        "all_solutions": "Alle Lösungen",
        "back_to_blog": "Zurück zum Blog",
    },

    "footer": {
        "description": "KI-Vertriebsassistent, der rund um die Uhr Kundenanfragen beantwortet, Leads qualifiziert und an Ihr Vertriebsteam übergibt.",
        "nav_title": "Navigation",
        "legal_title": "Rechtliches",
        "contact_title": "Kontakt",
        "privacy": "Datenschutz",
        "terms": "AGB",
        "copyright": "SalesDesk AI. Alle Rechte vorbehalten.",
        "powered_by": "Technologie-Basis: NextBot",
    },

    "home": {
        "meta_title": "SalesDesk AI — KI-Sales-Bot 24/7 | Vertriebsautomatisierung",
        "meta_desc": "KI-Vertriebsassistent 24/7: Sofortantwort, Lead-Qualifizierung, Übergabe an Ihr Team. Implementierung in 24–48 Stunden.",
        "hero_title": "Leads warten nicht",
        "hero_highlight": "SalesDesk AI antwortet sofort",
        "hero_desc": "Ihr KI-Vertriebsassistent arbeitet rund um die Uhr: beantwortet Anfragen in Sekunden, qualifiziert Leads und übergibt sie an Ihr Team. Kein Lead geht verloren.",
        "hero_cta_primary": "Demo testen",
        "hero_cta_secondary": "Komplettlösung anfragen",

        "problems_title": "Kommt Ihnen das bekannt vor?",
        "problems": [
            {"icon": "clock", "title": "Anfragen gehen verloren", "desc": "Ein Kunde schreibt um 23 Uhr — die Antwort kommt erst am nächsten Morgen. Zu spät: Er ist beim Wettbewerb."},
            {"icon": "users", "title": "Ihr Team ist überlastet", "desc": "80 % der Fragen wiederholen sich. Ihr Vertrieb verbringt Zeit mit FAQ statt mit Abschlüssen."},
            {"icon": "trending-down", "title": "Kein Follow-up", "desc": "Interessenten fragen an und verschwinden. Niemand erinnert, klärt nach oder schließt ab."},
        ],

        "solution_title": "So löst SalesDesk AI das",
        "solution_steps": [
            {"icon": "zap", "title": "Sofortantwort", "desc": "Der Bot antwortet in 2–3 Sekunden — zu jeder Tages- und Nachtzeit."},
            {"icon": "filter", "title": "Qualifizierung", "desc": "KI stellt gezielte Fragen, erkennt Bedarf und Budget. Ihr Team erhält qualifizierte Leads."},
            {"icon": "repeat", "title": "Follow-up", "desc": "Automatische Erinnerungen und Follow-up-Sequenzen. Kein Interessent wird vergessen."},
            {"icon": "user-check", "title": "Übergabe ans Team", "desc": "Wenn der Lead bereit ist — übergibt der Bot das Gespräch mit vollem Kontext an Ihr Team."},
        ],

        "industries_title": "Für Ihre Branche optimiert",
        "industries_desc": "SalesDesk AI passt sich an die Anforderungen Ihres Geschäfts an",

        "stats_title": "Warum Unternehmen auf KI-Vertrieb setzen",
        "stats": [
            {"value": "24/7", "label": "Verfügbarkeit"},
            {"value": "2–3 Sek", "label": "Antwortzeit"},
            {"value": "24–48 h", "label": "Implementierung"},
            {"value": "0", "label": "Verlorene Leads"},
        ],

        "process_title": "Start in 3 Schritten",
        "process_steps": [
            {"num": "01", "title": "Briefing", "desc": "Beschreiben Sie Ihr Geschäft, Ihre Leistungen und typische Kundenanfragen."},
            {"num": "02", "title": "Einrichtung", "desc": "Wir erstellen Szenarien, laden Ihre Wissensbasis und testen alles gründlich."},
            {"num": "03", "title": "Go-Live", "desc": "Anbindung an Ihre Kanäle und Schulung Ihres Teams."},
        ],

        "guarantee_title": "Prozessgarantie",
        "guarantee_desc": "Wir garantieren die Implementierung Ihres KI-Bots innerhalb von 24–48 Stunden nach Bereitstellung aller Materialien. Schaffen wir es nicht — erstatten wir die Einrichtungsgebühr.",

        "faq_title": "Häufige Fragen",
        "faq": [
            {"q": "Was ist SalesDesk AI?", "a": "SalesDesk AI ist ein KI-Vertriebsassistent, der rund um die Uhr arbeitet. Er beantwortet Kundenanfragen, qualifiziert Leads und übergibt sie an Ihr Vertriebsteam. Technologische Basis ist die NextBot-Plattform."},
            {"q": "Wie schnell kann ich starten?", "a": "Mit dem Komplettpaket in 24–48 Stunden ab Bereitstellung Ihrer Materialien (FAQ, Preisliste, Leistungsbeschreibung). Selbsteinrichtung ab 10 Minuten."},
            {"q": "Ersetzt der Bot meinen Vertrieb?", "a": "Nein. Der Bot übernimmt Routineaufgaben: Erstantworten, Qualifizierung, FAQ. Ihr Team erhält vorqualifizierte Leads und konzentriert sich auf Abschlüsse."},
            {"q": "Welche Kanäle werden unterstützt?", "a": "Telegram, WhatsApp, Instagram Direct, Website-Widget, Facebook Messenger — abhängig vom gewählten Paket."},
            {"q": "Was passiert bei falschen Antworten?", "a": "Der Bot arbeitet ausschließlich mit Ihrer Wissensbasis. Bei unklaren Anfragen leitet er an einen Mitarbeiter weiter. Vor dem Start testen wir alle Szenarien."},
            {"q": "Was kostet es?", "a": "Es gibt 4 Pakete: von der Selbsteinrichtung (kostenfrei unsererseits) bis zur vollständigen CRM-Integration. Details auf der Preisseite."},
        ],
    },

    "solutions": {
        "meta_title": "SalesDesk AI Lösungen nach Branche | KI-Bot für Ihr Geschäft",
        "meta_desc": "KI-Sales-Bot für Kosmetik, Bildung, Kliniken, Werkstätten, Gastronomie, Immobilien und Einzelhandel. Einrichtung in 24–48 Stunden.",
        "title": "Lösungen für Ihre Branche",
        "desc": "SalesDesk AI passt sich an Ihre Branche an. Wählen Sie Ihren Bereich — wir zeigen, wie der KI-Bot bei Ihnen arbeitet.",
        "niches": {
            "beauty": {
                "name": "Kosmetik & Salons",
                "icon": "sparkles",
                "short_desc": "KI-Bot für Schönheitssalons, Kosmetikstudios und Barbershops",
                "meta_title": "KI-Bot für Schönheitssalons | SalesDesk AI",
                "meta_desc": "Automatisieren Sie Terminbuchungen und Beratungen in Ihrem Salon. KI-Bot antwortet 24/7, bucht Termine und erinnert an Besuche.",
                "hero_title": "KI-Rezeption für Ihren Salon",
                "hero_desc": "Kunden schreiben außerhalb der Öffnungszeiten? Ihre Rezeption kommt nicht hinterher? SalesDesk AI arbeitet rund um die Uhr: berät zu Leistungen und Preisen, bucht Termine und erinnert an Besuche.",
                "problems": [
                    "Kunden schreiben um 22 Uhr — die Antwort kommt erst am nächsten Morgen",
                    "Die Rezeption ist mit Telefonaten überlastet und kann nicht auf Messenger antworten",
                    "Keine automatischen Erinnerungen — Kunden vergessen Termine",
                    "Neukunden erhalten keine Beratung zu Leistungen und gehen woanders hin",
                ],
                "how_it_works": [
                    {"title": "Leistungsberatung", "desc": "Der Bot kennt alle Preise, Behandlungsbeschreibungen und Kontraindikationen. Antwortet sofort auf alle Fragen."},
                    {"title": "Online-Terminbuchung", "desc": "Kunden wählen Behandlung, Mitarbeiter und Wunschtermin direkt im Chat."},
                    {"title": "Erinnerungen", "desc": "Automatische Erinnerung einen Tag und eine Stunde vor dem Termin. Reduziert No-Shows."},
                    {"title": "Übergabe an Mitarbeiter", "desc": "Komplexe Fragen (Allergien, individuelle Behandlungen) werden sofort an die Rezeption weitergeleitet."},
                ],
                "result_title": "Ergebnis",
                "results": [
                    "Keine Anfrage geht verloren — auch nachts nicht",
                    "Rezeption konzentriert sich auf Kunden vor Ort statt auf Chats",
                    "Weniger No-Shows durch automatische Erinnerungen",
                    "Mehr Buchungen über Messenger und Social Media",
                ],
            },
            "education": {
                "name": "Bildung & Kurse",
                "icon": "graduation-cap",
                "short_desc": "KI-Bot für Online-Schulen, Kurse und Bildungszentren",
                "meta_title": "KI-Bot für Bildung und Kurse | SalesDesk AI",
                "meta_desc": "Automatisieren Sie die Bearbeitung von Kursanfragen. KI-Bot berät zu Programmen, beantwortet Fragen und nimmt Anmeldungen entgegen — 24/7.",
                "hero_title": "KI-Assistent für Ihr Bildungsgeschäft",
                "hero_desc": "Interessenten stellen immer die gleichen Fragen: Programm, Dauer, Kosten, Format. SalesDesk AI übernimmt das — antwortet sofort, hilft bei der Kurswahl und führt zur Anmeldung.",
                "problems": [
                    "Berater beantworten hundertmal täglich die gleichen Fragen",
                    "Anfragen von Website und Social Media werden zu langsam bearbeitet",
                    "Kein Follow-up: Interessent fragt nach einem Kurs und verschwindet",
                    "In der Anmeldesaison ist das Team völlig überlastet",
                ],
                "how_it_works": [
                    {"title": "Programmberatung", "desc": "Der Bot kennt alle Kurse, Zeitpläne, Preise und Formate. Hilft bei der passenden Auswahl."},
                    {"title": "Qualifizierung", "desc": "Ermittelt Vorkenntnisse, Lernziele und Budget. Empfiehlt die optimale Option."},
                    {"title": "Follow-up", "desc": "Wenn sich der Interessent nicht sofort anmeldet, erinnert der Bot und beantwortet weitere Fragen."},
                    {"title": "Anmeldung", "desc": "Führt zur Kursanmeldung und kann einen Zahlungslink senden."},
                ],
                "result_title": "Ergebnis",
                "results": [
                    "Antwortzeit: Sekunden statt Stunden",
                    "Berater konzentrieren sich auf Verkäufe statt FAQ",
                    "Höhere Konversion von Anfrage zu Anmeldung durch Follow-up",
                    "Skalierung ohne zusätzliche Mitarbeiter",
                ],
            },
            "clinic": {
                "name": "Kliniken & Zahnärzte",
                "icon": "heart-pulse",
                "short_desc": "KI-Bot für medizinische Kliniken und Zahnarztpraxen",
                "meta_title": "KI-Bot für Kliniken und Zahnärzte | SalesDesk AI",
                "meta_desc": "KI-Assistent für medizinische Einrichtungen: Terminbuchung, Leistungsberatung, Patientenerinnerungen. Rund um die Uhr verfügbar.",
            },
            "auto": {
                "name": "Autowerkstatt & Teilehandel",
                "icon": "car",
                "short_desc": "KI-Bot für Autowerkstätten und Ersatzteilhändler",
                "meta_title": "KI-Bot für Autowerkstätten | SalesDesk AI",
                "meta_desc": "Automatisieren Sie Auftragsannahme in der Werkstatt. KI-Bot berät zu Leistungen, nimmt Termine an und antwortet 24/7.",
            },
            "food": {
                "name": "Gastronomie & Lieferservice",
                "icon": "utensils",
                "short_desc": "KI-Bot für Restaurants, Cafés und Lieferdienste",
                "meta_title": "KI-Bot für Gastronomie | SalesDesk AI",
                "meta_desc": "KI-Assistent für die Gastronomie: Tischreservierung, Speisekarte, Bestellungen. Automatisierung des Bestellprozesses 24/7.",
            },
            "real-estate": {
                "name": "Immobilien & Renovierung",
                "icon": "building",
                "short_desc": "KI-Bot für Immobilienagenturen und Renovierungsfirmen",
                "meta_title": "KI-Bot für Immobilien | SalesDesk AI",
                "meta_desc": "Automatisieren Sie die Bearbeitung von Immobilienanfragen. KI-Bot qualifiziert Käufer, schlägt Objekte vor und bucht Besichtigungen.",
            },
            "retail": {
                "name": "Einzelhandel & Technik",
                "icon": "shopping-bag",
                "short_desc": "KI-Bot für Möbel-, Technik- und Einzelhandelsgeschäfte",
                "meta_title": "KI-Bot für den Einzelhandel | SalesDesk AI",
                "meta_desc": "KI-Berater für den Handel: Produktberatung, Verfügbarkeit, Lieferinformationen und Bestellannahme rund um die Uhr.",
            },
        },
    },

    "pricing": {
        "meta_title": "SalesDesk AI Preise | KI-Bot Implementierungspakete",
        "meta_desc": "4 Implementierungspakete für Ihren KI-Sales-Bot: von der Selbsteinrichtung bis zur vollständigen CRM-Integration.",
        "title": "Wählen Sie Ihr Paket",
        "desc": "Von der Selbsteinrichtung bis zur Komplettimplementierung mit CRM-Anbindung",
        "packages": [
            {
                "id": "self-serve",
                "name": "Self-Serve",
                "subtitle": "In 10 Minuten selbst einrichten",
                "price": "Kostenfrei",
                "price_note": "unsererseits",
                "features": [
                    "Selbstregistrierung auf der Plattform",
                    "Start-Checkliste von SalesDesk AI",
                    "Szenario-Vorlagen für Ihre Branche",
                    "Mini-Guide: Optimale Bot-Konfiguration",
                    "Zugang zur Wissensbasis und FAQ",
                ],
                "cta": "Kostenlos einrichten",
                "cta_type": "referral",
                "popular": False,
            },
            {
                "id": "lite",
                "name": "Lite",
                "subtitle": "Go-Live in 24–48 Stunden",
                "price": "ab 149 €",
                "price_note": "einmalige Einrichtung",
                "features": [
                    "Basis-Vertriebsszenario",
                    "Wissensbasis (FAQ, Leistungen, Preise)",
                    "Test vor Go-Live",
                    "Anbindung an 1 Kanal",
                    "3 Tage Support nach Go-Live",
                    "Garantie: Go-Live oder Geld zurück",
                ],
                "cta": "Einrichtung bestellen",
                "cta_type": "contact",
                "popular": False,
            },
            {
                "id": "pro",
                "name": "Pro",
                "subtitle": "Multikanal + Follow-up",
                "price": "ab 349 €",
                "price_note": "einmalige Einrichtung",
                "features": [
                    "Alles aus Lite +",
                    "Lead-Segmentierung nach Anfragetyp",
                    "Follow-up-Sequenzen",
                    "Verschiedene Szenario-Pfade",
                    "Anbindung an bis zu 3 Kanäle",
                    "Reporting und Analyse",
                    "14 Tage Support und Optimierung",
                ],
                "cta": "Pro wählen",
                "cta_type": "contact",
                "popular": True,
            },
            {
                "id": "max",
                "name": "Max / Enterprise",
                "subtitle": "Vollständige Integration",
                "price": "Auf Anfrage",
                "price_note": "individuell",
                "features": [
                    "Alles aus Pro +",
                    "CRM / Google Sheets Integration",
                    "Komplexe bedingte Szenarien",
                    "Team-Schulung",
                    "SLA und Prioritäts-Support",
                    "30 Tage Begleitung",
                    "Dedizierter Projektmanager",
                ],
                "cta": "Projekt besprechen",
                "cta_type": "contact",
                "popular": False,
            },
        ],
        "note": "NextBot-Plattformgebühren werden separat berechnet. Aktuelle Plattformpreise bei der Registrierung.",
        "faq_title": "Fragen zu den Preisen",
        "faq": [
            {"q": "Was ist im Paketpreis enthalten?", "a": "Die Paketpreise von SalesDesk AI sind einmalige Gebühren für Einrichtung und Implementierung. Das NextBot-Plattformabonnement wird separat nach den Plattformtarifen berechnet."},
            {"q": "Kann ich das Paket wechseln?", "a": "Ja, Sie können jederzeit auf ein höherwertiges Paket upgraden und zahlen nur die Differenz."},
            {"q": "Was bedeutet Prozessgarantie?", "a": "Wir garantieren den Bot-Launch im vereinbarten Zeitrahmen, sofern Sie alle erforderlichen Materialien bereitstellen. Schaffen wir es nicht, erstatten wir die Einrichtungsgebühr."},
        ],
    },

    "demo": {
        "meta_title": "SalesDesk AI Demo | KI-Sales-Bot testen",
        "meta_desc": "Testen Sie den KI-Vertriebsassistenten direkt auf unserer Website. Sehen Sie, wie der Bot Fragen beantwortet und Leads qualifiziert.",
        "title": "Testen Sie SalesDesk AI",
        "desc": "Probieren Sie den KI-Bot live aus. Stellen Sie Fragen wie ein echter Kunde — und erleben Sie, wie der Bot antwortet und qualifiziert.",
        "widget_title": "Demo-Widget",
        "widget_fallback": "Falls das Widget nicht lädt — testen Sie den Bot in Telegram",
        "tips_title": "So testen Sie richtig",
        "tips": [
            "Fragen Sie nach Leistungen und Preisen — wie ein echter Kunde",
            "Stellen Sie eine themenfremde Frage — sehen Sie, wie der Bot reagiert",
            "Stellen Sie eine Nachfrage — bewerten Sie die Antworttiefe",
            "Bitten Sie um Verbindung mit einem Mitarbeiter — prüfen Sie die Übergabe",
        ],
        "faq_title": "Fragen zur Demo",
        "faq": [
            {"q": "Ist das ein echter KI-Bot?", "a": "Ja, ein funktionierender Bot auf der NextBot-Plattform, konfiguriert als Demo für SalesDesk AI."},
            {"q": "Kann ich so einen Bot für mein Unternehmen bekommen?", "a": "Selbstverständlich. Wählen Sie ein Paket auf der Preisseite oder kontaktieren Sie uns per Telegram."},
            {"q": "Werden meine Demo-Daten gespeichert?", "a": "Die Demo dient nur zum Testen. Bitte geben Sie keine echten personenbezogenen Daten ein."},
        ],
    },

    "about": {
        "meta_title": "Über SalesDesk AI | KI-Vertriebslösungen Integrator",
        "meta_desc": "SalesDesk AI — Ihr Integrator für KI-Vertriebslösungen. Wir richten KI-Bots für Ihr Geschäft in 24–48 Stunden ein.",
        "title": "Über SalesDesk AI",
        "intro": "Wir sind das Team von SalesDesk AI — Ihr Integrator für KI-gestützte Vertriebsautomatisierung. Wir helfen Unternehmen in Deutschland und Europa, KI-Vertriebsassistenten schnell und zuverlässig zu implementieren.",
        "mission_title": "Unsere Mission",
        "mission": "KI-Vertrieb für den Mittelstand zugänglich machen. Keine IT-Abteilung nötig — wir richten alles schlüsselfertig ein.",
        "principles": [
            {"title": "Geschwindigkeit", "desc": "Go-Live in 24–48 Stunden statt Monaten. Sie generieren sofort Leads."},
            {"title": "Transparenz", "desc": "Klare Preise, klarer Prozess. Keine versteckten Kosten."},
            {"title": "Prozessgarantie", "desc": "Wir stehen für Termine und Qualität ein. Nicht geliefert — Geld zurück."},
            {"title": "Begleitung", "desc": "Wir lassen Sie nach der Einrichtung nicht allein. Optimierung und Skalierung inklusive."},
        ],
        "tech_title": "Technologie",
        "tech_desc": "SalesDesk AI basiert auf der NextBot-Plattform — einer modernen KI-Plattform für intelligente Vertriebsbots. Als offizieller Integrator helfen wir Unternehmen, das volle Potenzial der Plattform zu nutzen.",
    },

    "contact": {
        "meta_title": "SalesDesk AI Kontakt | Nehmen Sie Kontakt auf",
        "meta_desc": "Kontaktieren Sie SalesDesk AI: Telegram, E-Mail, Kontaktformular. Antwort innerhalb einer Stunde während der Geschäftszeiten.",
        "title": "Kontakt aufnehmen",
        "desc": "Beschreiben Sie Ihr Geschäft — wir schlagen die optimale Lösung vor",
        "form_title": "Anfrage senden",
        "form_name": "Ihr Name",
        "form_phone": "Telefon oder Telegram",
        "form_business": "Geschäftstyp",
        "form_message": "Beschreiben Sie kurz Ihre Anforderung",
        "form_submit": "Anfrage senden",
        "form_success": "Anfrage gesendet! Wir melden uns in Kürze bei Ihnen.",
        "form_error": "Sendefehler. Bitte versuchen Sie es erneut oder kontaktieren Sie uns per Telegram.",
        "telegram_title": "Oder schreiben Sie uns in Telegram",
        "telegram_desc": "Der schnellste Weg, eine Frage zu stellen oder Ihr Projekt zu besprechen",
    },

    "privacy": {
        "meta_title": "Datenschutzerklärung | SalesDesk AI",
        "meta_desc": "Datenschutzerklärung von SalesDesk AI. Erfahren Sie, wie wir Ihre personenbezogenen Daten verarbeiten und schützen.",
        "title": "Datenschutzerklärung",
        "updated": "Letzte Aktualisierung: Januar 2026",
        "sections": [
            {"title": "Welche Daten wir erheben", "text": "Bei Nutzung unserer Website und Kontaktformulare können wir folgende Daten erheben: Name, Telefonnummer oder Telegram-Handle, Geschäftstyp und Anforderungsbeschreibung. Ohne Ihre Einwilligung erheben wir keine Daten automatisch."},
            {"title": "Verwendung der Daten", "text": "Die erhobenen Daten verwenden wir ausschließlich zur Kontaktaufnahme bezüglich Ihrer Anfrage, zur Empfehlung der optimalen Lösung und zur Verbesserung unseres Services."},
            {"title": "Analytik und Cookies", "text": "Auf unserer Website können Analysedienste (Google Analytics, Meta Pixel) zur Besucheranalyse eingesetzt werden. Diese Dienste verwenden Cookies. Sie können Cookies über den Einwilligungsbanner ablehnen. Ohne Ihre Zustimmung werden keine Analyse-Cookies gesetzt."},
            {"title": "Weitergabe an Dritte", "text": "Wir verkaufen oder übermitteln Ihre personenbezogenen Daten nicht an Dritte, außer in gesetzlich vorgeschriebenen Fällen."},
            {"title": "Datenspeicherung", "text": "Daten werden auf gesicherten Servern gespeichert. Wir treffen angemessene Maßnahmen zum Schutz vor unbefugtem Zugriff."},
            {"title": "Ihre Rechte", "text": "Sie können die Löschung Ihrer Daten beantragen, indem Sie uns über das Kontaktformular oder Telegram kontaktieren. Gemäß DSGVO haben Sie das Recht auf Auskunft, Berichtigung und Löschung Ihrer Daten."},
        ],
    },

    "terms": {
        "meta_title": "AGB | SalesDesk AI",
        "meta_desc": "Allgemeine Geschäftsbedingungen für die Nutzung der SalesDesk AI Website und Services.",
        "title": "Allgemeine Geschäftsbedingungen",
        "updated": "Letzte Aktualisierung: Januar 2026",
        "sections": [
            {"title": "Allgemeines", "text": "Diese AGB regeln die Nutzung der SalesDesk AI Website. Durch die Nutzung stimmen Sie diesen Bedingungen zu."},
            {"title": "Leistungen", "text": "SalesDesk AI bietet Einrichtungs- und Implementierungsservices für KI-Vertriebsbots auf Basis der NextBot-Plattform. Der genaue Leistungsumfang richtet sich nach dem gewählten Paket."},
            {"title": "Garantien", "text": "SalesDesk AI garantiert die Durchführung der Arbeiten im vereinbarten Zeitrahmen, sofern der Kunde alle erforderlichen Materialien bereitstellt. Wir garantieren keine konkreten finanziellen Ergebnisse."},
            {"title": "Zahlung", "text": "Die Zahlung für SalesDesk AI Services erfolgt gemäß dem gewählten Paket. Das NextBot-Plattformabonnement wird separat gemäß den Plattformtarifen berechnet."},
            {"title": "Haftung", "text": "SalesDesk AI haftet nicht für den Betrieb der NextBot-Plattform, Ausfälle von Messenger-Diensten und Drittanbietern."},
        ],
    },

    "blog": {
        "meta_title": "SalesDesk AI Blog | Artikel über KI-Vertrieb",
        "meta_desc": "Nützliche Artikel über Vertriebsautomatisierung, KI-Bots und digitales Marketing. Tipps, Referenzen und Anleitungen vom SalesDesk AI Team.",
        "title": "Blog",
        "desc": "Artikel über Vertriebsautomatisierung und KI-Technologien",
        "read_also": "Lesen Sie auch",
        "next_step": "Nächster Schritt: Testen Sie den KI-Bot live",
        "categories": {
            "automation": "Automatisierung",
            "cases": "Referenzen",
            "guides": "Anleitungen",
            "trends": "Trends",
        },
    },

    "cases": {
        "meta_title": "SalesDesk AI Referenzen | KI-Bot Implementierungsbeispiele",
        "meta_desc": "Praxisbeispiele für KI-Bot-Implementierungen. Anonymisierte Referenzen aus verschiedenen Branchen.",
        "title": "Referenzen und Szenarien",
        "desc": "Beispiele, wie SalesDesk AI in verschiedenen Branchen arbeitet",
        "coming_soon": "Dieser Bereich wird gerade erstellt. Bald finden Sie hier echte Referenzen aus verschiedenen Branchen.",
    },

    "breadcrumbs": {
        "home": "Startseite",
        "solutions": "Lösungen",
        "pricing": "Preise",
        "demo": "Demo",
        "blog": "Blog",
        "cases": "Referenzen",
        "about": "Über uns",
        "contact": "Kontakt",
        "privacy": "Datenschutz",
        "terms": "AGB",
    },

    "consent": {
        "text": "Wir verwenden Cookies für Analysezwecke. Gemäß DSGVO benötigen wir Ihre Zustimmung.",
        "accept": "Akzeptieren",
        "decline": "Ablehnen",
    },

    "not_found": {
        "title": "Seite nicht gefunden",
        "desc": "Die Seite wurde möglicherweise verschoben oder gelöscht.",
        "cta": "Zur Startseite",
    },
}
